# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/river/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/river/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/motorola/river/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/motorola/river/proprietary/etc/permissions/audiosphere.xml:system/etc/permissions/audiosphere.xml \
    vendor/motorola/river/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/motorola/river/proprietary/etc/permissions/com.nxp.nfc.xml:system/etc/permissions/com.nxp.nfc.xml \
    vendor/motorola/river/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/motorola/river/proprietary/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:system/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/motorola/river/proprietary/etc/permissions/com.qualcomm.qti.imscmservice.xml:system/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/motorola/river/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/motorola/river/proprietary/etc/permissions/embms.xml:system/etc/permissions/embms.xml \
    vendor/motorola/river/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/motorola/river/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/motorola/river/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/motorola/river/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/motorola/river/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/motorola/river/proprietary/framework/audiosphere.jar:system/framework/audiosphere.jar \
    vendor/motorola/river/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/motorola/river/proprietary/framework/com.nxp.nfc.jar:system/framework/com.nxp.nfc.jar \
    vendor/motorola/river/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/motorola/river/proprietary/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar:system/framework/com.qualcomm.qti.imscmservice-V2.1-java.jar \
    vendor/motorola/river/proprietary/framework/com.qualcomm.qti.uceservice-V2.0-java.jar:system/framework/com.qualcomm.qti.uceservice-V2.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/motorola/river/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/motorola/river/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/motorola/river/proprietary/framework/embmslibrary.jar:system/framework/embmslibrary.jar \
    vendor/motorola/river/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/motorola/river/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/motorola/river/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.data.factory-V1.0-java.jar:system/framework/vendor.qti.data.factory-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.hardware.data.latency-V1.0-java.jar:system/framework/vendor.qti.hardware.data.latency-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.hardware.soter-V1.0-java.jar:system/framework/vendor.qti.hardware.soter-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.ims.callinfo-V1.0-java.jar:system/framework/vendor.qti.ims.callinfo-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar:system/framework/vendor.qti.ims.rcsconfig-V1.0-java.jar \
    vendor/motorola/river/proprietary/framework/vendor.qti.latency-V2.0-java.jar:system/framework/vendor.qti.latency-V2.0-java.jar \
    vendor/motorola/river/proprietary/lib/com.qualcomm.qti.imscmservice@1.0.so:system/lib/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/motorola/river/proprietary/lib/com.qualcomm.qti.imscmservice@2.0.so:system/lib/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/motorola/river/proprietary/lib/com.qualcomm.qti.imscmservice@2.1.so:system/lib/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/motorola/river/proprietary/lib/com.qualcomm.qti.uceservice@2.0.so:system/lib/com.qualcomm.qti.uceservice@2.0.so \
    vendor/motorola/river/proprietary/lib/extractors/libmmparser.so:system/lib/extractors/libmmparser.so \
    vendor/motorola/river/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/motorola/river/proprietary/lib/lib-imscamera.so:system/lib/lib-imscamera.so \
    vendor/motorola/river/proprietary/lib/lib-imsvideocodec.so:system/lib/lib-imsvideocodec.so \
    vendor/motorola/river/proprietary/lib/lib-imsvt.so:system/lib/lib-imsvt.so \
    vendor/motorola/river/proprietary/lib/lib-imsvtextutils.so:system/lib/lib-imsvtextutils.so \
    vendor/motorola/river/proprietary/lib/lib-imsvtutils.so:system/lib/lib-imsvtutils.so \
    vendor/motorola/river/proprietary/lib/libFileMux.so:system/lib/libFileMux.so \
    vendor/motorola/river/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/motorola/river/proprietary/lib/libimscamera_jni.so:system/lib/libimscamera_jni.so \
    vendor/motorola/river/proprietary/lib/libimsmedia_jni.so:system/lib/libimsmedia_jni.so \
    vendor/motorola/river/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/motorola/river/proprietary/lib/libmmparser_lite.so:system/lib/libmmparser_lite.so \
    vendor/motorola/river/proprietary/lib/libmmrtpdecoder.so:system/lib/libmmrtpdecoder.so \
    vendor/motorola/river/proprietary/lib/libmmrtpencoder.so:system/lib/libmmrtpencoder.so \
    vendor/motorola/river/proprietary/lib/libwfdavenhancements.so:system/lib/libwfdavenhancements.so \
    vendor/motorola/river/proprietary/lib/libwfdmmsink.so:system/lib/libwfdmmsink.so \
    vendor/motorola/river/proprietary/lib/libwfduibcsink.so:system/lib/libwfduibcsink.so \
    vendor/motorola/river/proprietary/lib/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.hardware.vpp@1.1.so:system/lib/vendor.qti.hardware.vpp@1.1.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.ims.callinfo@1.0.so:system/lib/vendor.qti.ims.callinfo@1.0.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.ims.rcsconfig@1.0.so:system/lib/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.imsrtpservice@1.0.so:system/lib/vendor.qti.imsrtpservice@1.0.so \
    vendor/motorola/river/proprietary/lib/vendor.qti.latency@2.0.so:system/lib/vendor.qti.latency@2.0.so \
    vendor/motorola/river/proprietary/lib64/com.qualcomm.qti.imscmservice@1.0.so:system/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    vendor/motorola/river/proprietary/lib64/com.qualcomm.qti.imscmservice@2.0.so:system/lib64/com.qualcomm.qti.imscmservice@2.0.so \
    vendor/motorola/river/proprietary/lib64/com.qualcomm.qti.imscmservice@2.1.so:system/lib64/com.qualcomm.qti.imscmservice@2.1.so \
    vendor/motorola/river/proprietary/lib64/com.qualcomm.qti.uceservice@2.0.so:system/lib64/com.qualcomm.qti.uceservice@2.0.so \
    vendor/motorola/river/proprietary/lib64/extractors/libmmparser.so:system/lib64/extractors/libmmparser.so \
    vendor/motorola/river/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/motorola/river/proprietary/lib64/lib-imscamera.so:system/lib64/lib-imscamera.so \
    vendor/motorola/river/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/motorola/river/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/motorola/river/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/motorola/river/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/motorola/river/proprietary/lib64/libFileMux.so:system/lib64/libFileMux.so \
    vendor/motorola/river/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/motorola/river/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/motorola/river/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/motorola/river/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/motorola/river/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/motorola/river/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/motorola/river/proprietary/lib64/libmmosal.so:system/lib64/libmmosal.so \
    vendor/motorola/river/proprietary/lib64/libmmparser_lite.so:system/lib64/libmmparser_lite.so \
    vendor/motorola/river/proprietary/lib64/libmmrtpdecoder.so:system/lib64/libmmrtpdecoder.so \
    vendor/motorola/river/proprietary/lib64/libmmrtpencoder.so:system/lib64/libmmrtpencoder.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.hardware.soter@1.0.so:system/lib64/vendor.qti.hardware.soter@1.0.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.hardware.vpp@1.1.so:system/lib64/vendor.qti.hardware.vpp@1.1.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.ims.callinfo@1.0.so:system/lib64/vendor.qti.ims.callinfo@1.0.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.ims.rcsconfig@1.0.so:system/lib64/vendor.qti.ims.rcsconfig@1.0.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/motorola/river/proprietary/lib64/vendor.qti.latency@2.0.so:system/lib64/vendor.qti.latency@2.0.so

PRODUCT_PACKAGES += \
    vendor.qti.hardware.fm@1.0 \
    QtiTelephonyService \
    datastatusnotification \
    embms \
    CNEService \
    ims \
    qcrilmsgtunnel
